stages:
  - test

cypress-test:
  stage: test
  image: cypress/browsers:node16.14.2-chrome99-ff97
  before_script:
    - npm install
  script:
    - npx cypress run --browser chrome --headless
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 7 days
