name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6  # Atualizado para v6
        with:
          browser: chrome
          headless: true
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: cypress-videos
          path: cypress/videos
