name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-chrome99-ff97
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/
